version: '3'

networks:
  gateway:
    external: true
  cluster-bt:
    driver: bridge

services:
  mongodb-verbraucher:
    image: mongo:latest
    container_name: "mongodb-verbraucher"
    command: mongod --port 27011
    networks:
      - gateway
      - cluster-bt
  app:
    build:
      context: .
    container_name: "batutourism-verbraucher"
    environment:
      DB_URI: "mongodb://mongodb-verbraucher:27011/users"
    ports:
      - "3001:3001"
    depends_on:
      - mongodb-verbraucher
    networks:
      - gateway
      - cluster-bt
    expose:
      - "3001"
