version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb-verbraucher"
    ports:
        - 27011:27011
  app:
    build:
      context: .
    container_name: "batutourism-verbraucher"
    environment:
      DB_URI: "mongodb://mongodb:27011/users"
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
