enum BedType {
  DOUBLE
  SINGLE
}

type Reserved {
  from: String
  to: String
}

type Room {
  _id: String
  hotelId: String
  name: String
  guest: Int
  bedType: BedType
  size: Int
  roomNumber: Int
  price: Int
  description: String
  createdAt: String
  updatedAt: String
  reserved: [Reserved]
}

type Query {
  room(id: String!): Room
}

type Mutation {
  createRoom(hotelId: String!, name: String!, guest: Int!, bedType: BedType!, size: Int!, roomNumber: Int!, price: Int!, description: String!): Room!
  availableRoom(from: String!, to: String!, guest: Int!): [Room]!
}
