version: '3'

networks:
  gateway:
    external: true

services:
  app:
    build:
      context: .
    container_name: "batutourism-einfart"
    environment:
      SERVICE_USER: "http://localhost:3001"
      SERVICE_MASTER: "http://localhost:3002"
      SERVICE_BOOKING: "http://localhost:3003"
    ports:
      - "4000:4000"
    networks:
      - gateway
