version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb-meister"
    ports:
        - 27012:27012
  app:
    build:
      context: .
    container_name: "batutourism-meister"
    environment:
      DB_URI: "mongodb://mongodb:27012/master"
      USER_SERVICE: "http://localhost:3001"
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
