
version: "2"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
        - 27017:27017
  app:
    build:
      context: .
    container_name: "batutourism-auftrag"
    environment:
      MONGO: "mongodb://mongodb:27017/users"
    ports:
      - 3003:3003
